### ISSUE TITLE
Suggestion: Represent time instead of space / graphics-layer-specifics.

### ISSUE THREAD

**Issue by acdemiralp** [openscenegraph/VulkanSceneGraph#1]
Hello,

As part of the research phase, I wanted to inform you of the following slides: https://www.gdcvault.com/play/1024612/FrameGraph-Extensible-Rendering-Architecture-in
The interesting part about EA's approach to the rendering layer is that they seem to no longer store explicit spatial information but instead represent time (one frame), as a graph of render tasks. Techniques which require spatial information such as LOD are implemented as render tasks and the information is explicitly provided to the render task. I have a toy implementation of this idea based on the slides at https://github.com/acdemiralp/fg . They call it render passes, I call them render tasks because a render pass is a specific concept in Vulkan that is not 1-1 with a render task.

I have rather historic experience with OpenSceneGraph, around 2012. From what I remember, it was responsible for building a scene hierarchy (similar to https://docs.unity3d.com/ScriptReference/Transform.html) + graphics layer specific hierarchical information (e.g. any mesh below this geode is going to be rendered with this shader and so on). Although these are two separate concerns in a modern setting. 

Almost every game engine uses the entity-component-system pattern to build scene hierarchies today. See https://www.youtube.com/watch?v=NTWSeQtHZ9M for a quick introduction. GDC 2018 also has content on this. I also have a naive implementation at https://github.com/acdemiralp/ecs and a more advanced data-driven one at https://github.com/acdemiralp/ec .  This is a layer above graphics, that is shared with other systems such as audio, physics, scripting etc. Hence it is not really within the context of a graphics library. I hope that the new library does not try to do everything, and end up with an internal ecs implementation + addons like vsgAudio, vsgPhysics etc which feel very invasive. It can expect the scene data to be provided by the user in a format it understands and do scene hierarchy dependent stuff like LOD from this information.

By invasiveness I mean: Once you add an OpenSceneGraph or Qt dependency to your project, it no longer feels like a C++ project, it feels like an OpenSceneGraph project or Qt project because too much inter-dependent functionality comes with the package. I hope that the new library does not do that and focus on graphics and do one thing extremely well. Something that takes the pain of creating bleeding-edge content with barebones Vulkan away (which is only possible by reading all of https://github.com/SaschaWillems/Vulkan at the moment). And which works with existing engines, integrable as a graphics layer or as the Vulkan implementation of a more general rendering backend. A beautiful example of a non-invasive library is https://github.com/ocornut/imgui

A basic engine + vsgViewer implementation could be developed on top of vsg as a separate library.

For a more C++ approach to Vulkan, I'd also suggest taking a look at: https://github.com/nvpro-pipeline/VkHLF as a base layer. It reduces the first triangle from ~1000 to ~200 lines.

**Comment by openscenegraph** [comment]
Thanks for the links.  FYI, the OpenSceneGraph already has support for controlling rendering passes and layers, so accomplishes much what the FrameGraph approach looks to do.  You also can control this all programmatically if you want to using cull callbacks or custom nodes. 

For the VulkanSceneGraph my plan is enable this same flexibility and power that the OpenSceneGraph has w.r.t multi-pass, multi-stage rendering, but I'll will look for ways to make it easier to set up and control. Vulkan has compute support directly as part of the API so I would like to enable the scene graph to be able to provide mechanisms for managing compute as well.  

One of the differences between the VulkanSceneGraph and OpenSceneGraph will be spatial data will be handled more explicitly in the new scene graph, giving the users ability to decide what type of data they want to store in a subgraph and how it should be culled if they so desire.  This will make it possible for users to create compute graphs/subgraphs, or for a single scene graph to have both spatial and non spatial subgraphs within it. 

It is my intention that VulkanSceneGraph will be smaller and more focused than the OpenSceneGraph, there won't be a collection of NodeKits and mass of loaders or examples bundled in. Instead my plan is for 3rd party libraries/frameworks to sit alongside (like osgEarth does for the OSG), or to encompass the VulkanSceneGraph as a component of their frameworks.

In terms of dependences, my aim is modern C++ (11 or later) and Vulkan, with possible native windowing built in (a decision on this has not yet been made.)  I don't plan on using any 3rd party layers on top of Vulkan, this does mean the VulkanSceneGraph codebase itself will need to encompass set up and management of Vulkan.  The way that Vulkan will be encapsulated is intended to be lightweight, without forcing certain setup on users, so while defaults will be provided, expert users will be able to take over various tasks themselves when they need to.  For the average user though, the aim will be to enable them to get a hello world application up with a dozen lines of code as you can with the OpenSceneGraph right now, but with the option for power users to have finer grained control.

We are less than 1/3rd the way through the Exploration Phase right now, once it's complete at the end of August we'll publish a design document which will outline the various approaches we'll take.  We aren't looking to debate with community during this phase, or look for wish list items.  Once this phase is complete then we can open out a bit further.  I am providing this reply not to start a discussion, just to give some clarifications.

**Comment by acdemiralp** [comment]
>> Thanks for the links. FYI, the OpenSceneGraph already has support for controlling rendering passes and layers, so accomplishes much what the FrameGraph approach looks to do. You also can control this all programmatically if you want to using cull callbacks or custom nodes.

Ah, I just went through the current codebase and saw the separate passes for stereo, depth peeling. Beautiful. And my bad for not doing this earlier.

>> For the VulkanSceneGraph my plan is enable this same flexibility and power that the OpenSceneGraph has w.r.t multi-pass, multi-stage rendering, but I'll will look for ways to make it easier to set up and control. Vulkan has compute support directly as part of the API so I would like to enable the scene graph to be able to provide mechanisms for managing compute as well.

I see. The only thing that bothers from an abstraction/naming point of view Graphics + Compute do not feel like something belonging to a Scene but to a Frame. A scene in modern context is a discrete 3D space containing objects(entities) which in turn may contain properties(components) such as transform, line_render, mesh_render, point_render, audio_source, audio_listener, rigidbody, etc. The objects might be hierarchically organized, which essentially turns the scene into a tree structure. It does not have a notion of being rendered or computed. It is just a bunch of objects in discrete 3D space, like us humans in the universe. A renderer may render a scene, possibly every frame. A physics engine might run physics simulations on the scene. An audio library might run 3D sound simulations and effects based on the audio listeners and sources in the scene. A step further, a vulkan_renderer may render a scene using Vulkan.

>> One of the differences between the VulkanSceneGraph and OpenSceneGraph will be spatial data will be handled more explicitly in the new scene graph, giving the users ability to decide what type of data they want to store in a subgraph and how it should be culled if they so desire. This will make it possible for users to create compute graphs/subgraphs, or for a single scene graph to have both spatial and non spatial subgraphs within it.

Isn't having a single scene graph and having both spatial and non-spatial subgraphs in it against separation of concerns? I see the scene and the set of render/compute tasks I need to do 60 times every second as completely separate things. I would understand if serialization was a concern and you wanted to store the full "state" for reconstructing the "scene/frame". But is this really what a graphics library should do? Or the engine consuming the graphics library should do? I genuinely wonder the answer to this.

>> It is my intention that VulkanSceneGraph will be smaller and more focused than the OpenSceneGraph, there won't be a collection of NodeKits and mass of loaders or examples bundled in. Instead my plan is for 3rd party libraries/frameworks to sit alongside (like osgEarth does for the OSG), or to encompass the VulkanSceneGraph as a component of their frameworks.

So a flatter project structure. That is great.

>> In terms of dependences, my aim is modern C++ (11 or later) and Vulkan, with possible native windowing built in (a decision on this has not yet been made.) I don't plan on using any 3rd party layers on top of Vulkan, this does mean the VulkanSceneGraph codebase itself will need to encompass set up and management of Vulkan. The way that Vulkan will be encapsulated is intended to be lightweight, without forcing certain setup on users, so while defaults will be provided, expert users will be able to take over various tasks themselves when they need to. For the average user though, the aim will be to enable them to get a hello world application up with a dozen lines of code as you can with the OpenSceneGraph right now, but with the option for power users to have finer grained control.

Nice! C++17 would be best with the addition of valuable features like std::any and std::variant. As a heads up, display and rendering are also separate concerns as much as e.g. audio and rendering. SDL2 is a de-facto standard at this, and supports all windowing systems that Vulkan supports to date. It is objectively hard to do what SDL2 does with a homemade solution, and doesn't make sense for a library to do what SDL2 does from scratch + graphics.

>> We are less than 1/3rd the way through the Exploration Phase right now, once it's complete at the end of August we'll publish a design document which will outline the various approaches we'll take. We aren't looking to debate with community during this phase, or look for wish list items. Once this phase is complete then we can open out a bit further. I am providing this reply not to start a discussion, just to give some clarifications.

Please do not take my words as arrogance or "wishlists from the community". I am only loud thinking what 1 particular superuser would expect this library to do. OpenSceneGraph came out at a time when there was no alternative. In 2018, there exists multiple open source libraries for high-level graphics and if VulkanSceneGraph tries to become more of a game engine-y framework like OpenSceneGraph rather than a thin graphics abstraction, it will be in the same lane as Godot, Unity and Unreal and probably lose the fight. If it happens to be an all-inclusive rendering layer, it will be in the same lane as bgfx and probably lose the fight since bgfx supports N render backends whereas VulkanSceneGraph given its name supports 1. But if VulkanSceneGraph becomes a thin rendering layer which I can push scene data to and gives me beautiful images rasterized/raytraced with Vulkan, which I can customize to do rendering or compute or both simultaneously, then I will certainly value VulkanSceneGraph over all the others.

**Comment by openscenegraph** [comment]
I'm closing this "Issue" as I'm not looking for wishlist items from the community or to keep rejecting pet ideas, one by one.  I have decades of experience with developing scene graphs and I have clear idea of what I am trying to achieve, but it's just not the time for general discussion. You just need to wait till I publish the design paper at the end of August.

**Comment by acdemiralp** [comment]
Alright, your approach to the community is along the lines of "stfu noobs" anyway, even in your other repositories. I thought only Linus got away with that. Apparently not.

I am just saying that it is retarded to roll your own windowing solution when SDL2 already exists. It is retarded to even consider having a windowing solution in a graphics library because display and graphics are two completely different things today. It is retarded to not use or at least have the humility to look into a high-level Vulkan wrapper written by f**king NVIDIA even if you have decades of experience building scene graphs. And you and your ideas belong to the 1990s. 

Scene graphs are dead. They only exist in CG101 assignments. Long live scene trees/hierarchies and renderers which render them, physics engines which simulate them, scripting engines which manipulate them. Long live the flexibility of being able to choose between OpenAL and FMOD and not being locked into osgAudio because of the shitty design of the rendering library that I am using.

- A man who tries to bury shit-abstracted-code-written-by-ancients-like-you into history.
